// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using muvinBackend.Data;

#nullable disable

namespace muvinBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("muvinBackend.Models.CaracteristicaImovel", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<double>("AreaUtil")
                        .HasColumnType("double precision")
                        .HasColumnName("area_util");

                    b.Property<int>("Banheiros")
                        .HasColumnType("integer")
                        .HasColumnName("banheiros");

                    b.Property<int>("Dormitorios")
                        .HasColumnType("integer")
                        .HasColumnName("dormitorios");

                    b.Property<int>("Suites")
                        .HasColumnType("integer")
                        .HasColumnName("suites");

                    b.Property<int>("Vagas")
                        .HasColumnType("integer")
                        .HasColumnName("vagas");

                    b.HasKey("Uuid");

                    b.ToTable("CaracteristicaImoveis");
                });

            modelBuilder.Entity("muvinBackend.Models.Corretor", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("text")
                        .HasColumnName("foto_perfil");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_completo");

                    b.Property<string>("NumCelular")
                        .HasColumnType("text")
                        .HasColumnName("num_celular");

                    b.Property<string>("RegistroCreci")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registro_creci");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.HasKey("Uuid");

                    b.ToTable("corretores");
                });

            modelBuilder.Entity("muvinBackend.Models.Endereco", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.HasKey("Uuid");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("muvinBackend.Models.FotoImovel", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("EnvioTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("envio_timestamp");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_foto");

                    b.HasKey("Uuid");

                    b.HasIndex("ImovelId");

                    b.ToTable("FotoImoveis");
                });

            modelBuilder.Entity("muvinBackend.Models.Imovel", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<Guid>("CaracteristicaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cod_interno");

                    b.Property<decimal>("CondominioMensal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("condominio_mensal");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<bool>("Destaque")
                        .HasColumnType("boolean")
                        .HasColumnName("destaque");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("uuid");

                    b.Property<int>("FinalidadeImovel")
                        .HasColumnType("integer")
                        .HasColumnName("finalidade_imovel");

                    b.Property<decimal>("IptuMensal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("iptu_mensal");

                    b.Property<decimal>("PrecoImovel")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("preco_imovel");

                    b.Property<DateTime>("PublicacaoTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicacao_timestamp");

                    b.Property<int>("StatusImovel")
                        .HasColumnType("integer")
                        .HasColumnName("status_imovel");

                    b.Property<int>("TipoImovel")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_imovel");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.HasKey("Uuid");

                    b.HasIndex("CaracteristicaId")
                        .IsUnique();

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("Imoveis");
                });

            modelBuilder.Entity("muvinBackend.Models.Lead", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<int>("Desejo")
                        .HasColumnType("integer")
                        .HasColumnName("desejo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("EnvioTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("envio_timestamp");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mensagem");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("NumCelular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("num_celular");

                    b.Property<int>("StatusLead")
                        .HasColumnType("integer")
                        .HasColumnName("status_lead");

                    b.HasKey("Uuid");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("muvinBackend.Models.FotoImovel", b =>
                {
                    b.HasOne("muvinBackend.Models.Imovel", "Imovel")
                        .WithMany("FotosImovel")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("muvinBackend.Models.Imovel", b =>
                {
                    b.HasOne("muvinBackend.Models.CaracteristicaImovel", "Caracteristica")
                        .WithOne("Imovel")
                        .HasForeignKey("muvinBackend.Models.Imovel", "CaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("muvinBackend.Models.Endereco", "Endereco")
                        .WithOne("Imovel")
                        .HasForeignKey("muvinBackend.Models.Imovel", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caracteristica");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("muvinBackend.Models.CaracteristicaImovel", b =>
                {
                    b.Navigation("Imovel")
                        .IsRequired();
                });

            modelBuilder.Entity("muvinBackend.Models.Endereco", b =>
                {
                    b.Navigation("Imovel")
                        .IsRequired();
                });

            modelBuilder.Entity("muvinBackend.Models.Imovel", b =>
                {
                    b.Navigation("FotosImovel");
                });
#pragma warning restore 612, 618
        }
    }
}
